app/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from app import views
urlpatterns = [
    url(r'^(?P<username>.*)/(?P<grade_id>\d+)/edit/(?P<questionnaire_id>\d+)',views.edit_questionnaire),
    url(r'^(?P<username>.*)/(?P<grade_id>\d+)/deloption/(?P<questionnaire_id>\d+)',views.del_question),
    url(r'^(?P<username>.*)/(?P<grade_id>\d+)/del/(?P<questionnaire_id>\d+)',views.del_questionnaire),
    url(r'^(?P<grade_id>\d+)/(?P<questionnaire_id>\d+)',views.see_questionnaire)
]

zny_question/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from app import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ss_login/', views.student_login),

    url(r'^login/', views.login),
    url(r'^questionnaire/', views.questionnaire),
    url(r'^question/', views.question),
    url(r'^student/',include('app.urls'))
]

app/models.py
from django.db import models

# Create your models here.
class Userinfo(models.Model):
    """
    员工表
    """
    username = models.CharField(max_length=32)
    password = models.CharField(max_length=32)
    grade=models.ForeignKey(to="Grade",verbose_name="班级")
    class Meta:
        verbose_name_plural="员工表"
    def __str__(self):
        return self.username

class Student(models.Model):
    """
    学生表
    """
    username = models.CharField(max_length=32)
    password = models.CharField(max_length=32)
    grade=models.ForeignKey(to="Grade",verbose_name="班级")
    class Meta:
        verbose_name_plural="学生表"
    def __str__(self):
        return self.username

class Grade(models.Model):
    """
    班级表
    """
    title=models.CharField(max_length=32)
    class Meta:
        verbose_name_plural="班级表"
    def __str__(self):
        return self.title
class Questionnaire(models.Model):
    """
    问卷表
    """
    caption=models.CharField(max_length=32)
    grade=models.ForeignKey(to="Grade",verbose_name="班级")
    creator = models.ForeignKey(to=Userinfo)
    class Meta:
        verbose_name_plural="问卷表"
    def __str__(self):
        return self.caption
class Question(models.Model):
    """
    问题表
    """
    caption=models.CharField(max_length=64)
    question_types = (
        (1, '打分'),
        (2, '单选'),
        (3, '评价'),
    )
    types = models.IntegerField(choices=question_types)
    questionnaire=models.ForeignKey("Questionnaire",verbose_name="关联问卷",default=None)
    class Meta:
        verbose_name_plural="问题表"
    def __str__(self):
        return self.caption

class Option(models.Model):
    """
    单选题的选项
    """
    name = models.CharField(verbose_name='选项名称',max_length=32)
    score = models.IntegerField(verbose_name='选项对应的分值')
    qs = models.ForeignKey(to=Question)
    class Meta:
        verbose_name_plural="单选题的选项"
    def __str__(self):
        return self.name

class Answer(models.Model):
    """
    回答
    """
    student = models.ForeignKey(to=Student)
    question = models.ForeignKey(to=Question,verbose_name="问题")

    val = models.IntegerField(null=True,blank=True)
    option=models.ForeignKey("Option",null=True,blank=True)
    content = models.CharField(max_length=255,null=True,blank=True)
    class Meta:
        verbose_name_plural="回答"
    def __str__(self):
        return self.student.username

templates/Questionnaire.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>问卷调查列表</title>
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/bootstrap.min.css">
</head>
<body>
<h1 class="text-center">问卷调查列表</h1>
<div class="container">
    <div class="pull-right">
        <button class="btn btn-success">添加问卷</button>
    </div>
    <div>
        <table class="table table-border table-hover" style="margin-top: 20px">
                     <tr>
                         <th>调查问卷名称</th>
                         <th>问卷调查班级</th>
                         <th>参与人数</th>
                         <th>问卷选项</th>
                         <th>调查地址</th>
                         <th>查看评分</th>
                         <th>操作</th>
                     </tr>
                    <tbody>
                    {% for obj in  questionnaire_list%}
                        <tr>
                        <td>{{ obj.caption }}</td>
                        <td>{{ obj.grade }}</td>
                        <td>
                        {{ obj.question_set.first.answer_set.all.count }}/{{ obj.grade.student_set.all.count }}
                            </td>
                        <td><a href="/student/{{ obj.creator.username }}/{{ obj.grade.id }}/edit/{{ obj.id }}">编辑问卷</a></td>
                        <td><a href="/student/{{ obj.grade.id }}/{{ obj.id }}">/student/{{ obj.grade.id }}/{{ obj.id }}</a></td>
                        <td><a>查看评分</a></td>
                        <td><button class="btn btn-danger">删除</button></td>
                        </tr>
                    {% endfor %}

                    </tbody>

                </table>

    </div>

</div>
</body>
</html>

templates/edit_Question.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/sweet/sweetalert2.min.css">
    <title>问卷调查</title>
    <style>
body {
  counter-reset: section;           /* 重置计数器成0 */
}
h3:before {
  counter-increment: section;      /* 增加计数器值 */
  content: "问题 " counter(section) " : "; /* 显示计数器 */
}
</style>

</head>

<body>
<h1 class="text-center">{{ questionnaire.caption }}</h1>
<div class="container">
    <div class="pull-right">
        <span class="error" style="color: darkred;font-size: 20px"></span>
        <button class="btn btn-success addquestion">添加</button>
        <button class="btn btn-info condtion">保存</button>
    </div>
    <div class="row">
        <div class="col-md-10">
            <form class="form-horizontal">
                <div class="col-md-10 col-lg-offset-2 quest_list" >
                    {% for obj in question_list %}
                        <div class="question" quest_id="{{ obj.id }}" >
                            <span class="glyphicon glyphicon-remove delquestion" style="line-height: 28px;float: right"></span>

                            <h3></h3>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">问题：</label>
                                <div class="col-sm-10">
                                    <textarea class="form-control textarea" rows="2"
                                              placeholder="问题" >{{ obj.caption }}</textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">类型：</label>
                                <div class="col-sm-6">
                                    <select size="1" class="form-control selector" >
                                        {% for type in type_list %}
                                            {% if obj.types == type.id %}
                                                <option selected value="{{ type.id }}">{{ type.type }}</option>
                                            {% else %}
                                                <option value="{{ type.id }}">{{ type.type }}</option>
                                            {% endif %}
                                        {% endfor type_list %}
                                    </select>
                                </div>
                                {% if obj.types == 2 %}
                                    <span class="glyphicon glyphicon-plus addoption"
                                          style="color: #2e6da4;line-height: 28px">添加选项</span>
                                {% endif %}
                            </div>
                            {% if obj.types == 2 %}
                            <div class="form-group">
                                    <label class="col-sm-2 control-label">选项：</label>
                                    <div class="col-sm-10">
                                    <ul>
                                        {% for option in obj.option_set.all %}

                                                <li option_id="{{ option.id }}">
                                                    <label class="col-sm-2 control-label">内容：</label>
                                                    <input type="text" class="col-sm-3 content" placeholder="内容" value="{{ option.name }}">
                                                    <label class="col-sm-2 control-label">分值：</label>
                                                    <input type="text" class="col-sm-3 score" placeholder="分值" value="{{ option.score }}">
                                                    <span class="glyphicon glyphicon-remove deloption" style="font-size: 18px;color: #cccccc;line-height: 28px;margin-left: 20px"></span>
                                                </li>

                                        {% endfor %}
                                      </ul>
                                    </div>
                                </div>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
            </form>
        </div>
    </div>

</div>
<div class="info" username="{{ questionnaire.creator.username }}" grade_id="{{ questionnaire.grade.id }}" questionnaire_id="{{ questionnaire.id }}"></div>
</body>
<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.js"></script>
<script src="https://cdn.bootcss.com/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
<script src="/static/sweet/sweetalert2.min.js"></script>
<script>
{#    选项改变#}
$(document).on("change",".selector",function () {
    var selectors=$(this).val();
    if (selectors == "2"){
        var netspan= '<span class="glyphicon glyphicon-plus addoption"style="color: #2e6da4;line-height: 28px">添加选项</span>';
        var option='<div class="form-group"> ' +
            '<label class="col-sm-2 control-label">选项：</label> ' +
            '<div class="col-sm-10">'+
                '<ul>' +
                    ' <li option_id="None">' +
{#                    ' <li >' +#}
                    ' <label class="col-sm-2 control-label">内容：</label> ' +
                    '<input type="text" class="col-sm-3 content" placeholder="内容"value="">'+
                    '<label class="col-sm-2 control-label">分值：</label>' +
                    ' <input type="text" class="col-sm-3 score" placeholder="分值" value=""> '+
                    ' <span class="glyphicon glyphicon-remove" style="font-size: 18px;color: #cccccc;line-height: 28px;margin-left: 20px"></span> ' +
                    '</li> ' +
                 '</ul></div> </div> ';
        $(this).parent().parent().append(netspan);
        $(this).parent().parent().parent().append(option);
    }else{
        $(this).parent().next().remove();
        $(this).parent().parent().next().remove()

    }

});
{#添加选项#}
$(document).on("click",".addoption",function () {
        var options='<li>' +
                    ' <label class="col-sm-2 control-label ">内容：</label> ' +
                    '<input type="text" class="col-sm-3 content" placeholder="内容">'+
                    '<label class="col-sm-2 control-label">分值：</label>' +
                    ' <input type="text" class="col-sm-3 score" placeholder="分值" > '+
                    ' <span class="glyphicon glyphicon-remove deloption" style="font-size: 18px;color: #cccccc;line-height: 28px;margin-left: 20px"></span> ' +
                    '</li>';
        $(this).parent().next().children().children().append(options)
    });
{#删除问题#}
 var username=$(".info").attr("username");
    var questionnaire_id=$(".info").attr("questionnaire_id");
    var grade_id=$(".info").attr("grade_id");
$(document).on("click",".delquestion",function () {
    var question_id=$(this).parent().attr("quest_id");
    var ss=$(this);
    $.ajax({
        url:'/student/'+username+'/'+grade_id+'/del/'+questionnaire_id,
        type:"post",
        headers: {"X-CSRFToken": $.cookie('csrftoken')},
        data:{question_id:question_id},
        success:function (data) {
            var datas=JSON.parse(data);
            if (datas.is_success){
                ss.parent().remove()
            }


        }

    });

});
{#删除选项#}
$(document).on("click",".deloption",function () {
    var option_id=$(this).parent().attr("option_id");
    var ss=$(this);
    $.ajax({
        url:'/student/'+username+'/'+grade_id+'/deloption/'+questionnaire_id,
        type:"post",
        headers: {"X-CSRFToken": $.cookie('csrftoken')},
        data:{option_id:option_id},
        success:function (data) {
            var datas=JSON.parse(data);
            if (datas.is_success){
                ss.parent().remove()
            }


        }});
});
{#添加问题#}
$(document).on("click",".addquestion",function () {
    ss=' <div class="question" quest_id="None" >'+
        '<span class="glyphicon glyphicon-remove delquestion" style="line-height: 28px;float: right"></span>' +
        ' <h3></h3>' +
        '<div class="form-group">' +
            ' <label class="col-sm-2 control-label">问题：</label>' +
            ' <div class="col-sm-10">' +
                ' <textarea class="form-control textarea" rows="2"placeholder="问题" ></textarea>'+
             '</div>' +
        ' </div>' +
        ' <div class="form-group">' +
            ' <label class="col-sm-2 control-label">类型：</label> ' +
            '<div class="col-sm-6">' +
                ' <select size="1" class="form-control selector" >' +
                     ' <option selected value="1">打分</option>' +
                    ' <option value="2">单选</option>' +
                     '<option value="3">评价</option>' +
                ' </select>' +
            ' </div>' +
        '</div>' +
    ' </div>';
    $(".quest_list").append(ss)
    });
{#保存#}
        $(document).on("click",".condtion",function () {
     quest_list=[];
    $(".quest_list>.question").each(function () {
         var questions_id=$(this).attr("quest_id");
         var quest_caption=$(this).find(".textarea").val();
         var quest_type=$(this).find(".selector").val();

         options=[];
         if (quest_type == 2){
         $(this).find("li").each(function () {

             var opp_id=$(this).attr("option_id");
             var content=$(this).find(".content").val();
             var score=$(this).find(".score").val();
             options.push({"opp_id":opp_id,"content":content,"score":score})

         });
         }
         if (quest_type == 2){
             quest_list.push({"questions_id":questions_id,"quest_caption":quest_caption,"quest_type":quest_type,"options":options})
         }else{
             quest_list.push({"questions_id":questions_id,"quest_caption":quest_caption,"quest_type":quest_type})

         }

    });

    $.ajax({
        url:'/student/'+username+'/'+grade_id+'/edit/'+questionnaire_id,
        type:'post',
        data: JSON.stringify(quest_list),
        headers: {"X-CSRFToken": $.cookie('csrftoken')},
        contentType:"application/json",
        success:function(data){
           var data=JSON.parse(data);
           if (data.is_success){
                swal(
                  'Oops...',
                  'Something went wrong!',
                  'ok'
                    )
           }else{
               $(".error").text(data.error);
               setTimeout(function () {
                            $('.error').text('')
                        }, 1000)
           }
        }

    })


    });
</script>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <title>登录</title>
     <style>
        body {
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #eee;
        }
    </style>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3 col-lg-offset-5" style="border-radius: 4px;margin-top: 100px">
            <form method="post" action="/login/">
                {% csrf_token %}
                  <div class="form-group">
                    <label for="username">用户名:</label>
                    <input type="text" class="form-control input-lg" name="username" id="username" placeholder="Username">
                  </div>
                  <div class="form-group">
                    <label for="password">密码:</label>
                    <input type="password" class="form-control input-lg" name="password" id="password" placeholder="Password">
                  </div>
                <div class="popup">
                     <div class="col-md-6">
                         <input type="submit" class="btn-primary form-control input-lg" value="登录" id="popup-submit" style="margin-left: -15px">
                     </div>
{#                    <div class="col-md-6">#}
{#                        <a href="/register/"><h3 class="pull-right register" style="margin-right: -15px">立即注册</h3></a>#}
{#                    </div>#}
                    <span class="error"></span>
                    <div id="popup-captcha"></div>
            </div>
            </form>

        </div>
    </div>

</div>

</body>
</html>

templates/questionnaire_answer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/bootstrap.min.css">
    <title>问卷调查</title>
    <style>

        ul>li{
            display: inline-block;
        }

    </style>
</head>
<body>
<h2 class="text-center">问卷调查</h2>
<div class="container">
    <form method="post" class="col-md-5 col-lg-offset-2" novalidate>
        {% csrf_token %}
    {% for fd in form %}
        <h4 class="">{{ fd.label }}
          {{ fd }}</h4>
        <span style="color: #a30000">{{ fd.errors.0 }}</span>
        {% endfor %}
<p>    <input type="submit" value="提交">
</p>
    </form>
</div>
</body>
</html>

templates/student_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <title>学生登录</title>
     <style>
        body {
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #eee;
        }
    </style>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3 col-lg-offset-5" style="border-radius: 4px;margin-top: 100px">
            <form method="post" action="/ss_login/">
                {% csrf_token %}
                  <div class="form-group">
                    <label for="username">用户名:</label>
                    <input type="text" class="form-control input-lg" name="username" id="username" placeholder="Username">
                  </div>
                  <div class="form-group">
                    <label for="password">密码:</label>
                    <input type="password" class="form-control input-lg" name="password" id="password" placeholder="Password">
                  </div>
                <div class="popup">
                     <div class="col-md-6">
                         <input type="submit" class="btn-primary form-control input-lg" value="登录" id="popup-submit" style="margin-left: -15px">
                     </div>
{#                    <div class="col-md-6">#}
{#                        <a href="/register/"><h3 class="pull-right register" style="margin-right: -15px">立即注册</h3></a>#}
{#                    </div>#}
                    <span class="error"></span>
                    <div id="popup-captcha"></div>
            </div>
            </form>

        </div>
    </div>

</div>

</body>
</html>